FROM node:16-alpine3.14
RUN addgroup app && adduser -SG app app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app . .

EXPOSE 3000
EXPOSE 4200
CMD ./bin/start-prod.sh